        
server:
  port: 3168

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
      - id: USERSERVICE
        uri: lb://USERSERVICE
        predicates:
        - Path=/users/** 
        
      - id: RATINGSERVICE
        uri: lb://RATINGSERVICE
        predicates:
        - Path=/rate/**
        
      - id: HOTELSERVICE
        uri: lb://HOTELSERVICE
        predicates:
        - Path=/hotel/**, /staffs/**         

  config:
    import: "configserver:http://localhost:3169"
            


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#   fetch-registry: true
#   service-url:
#      defaultZone: http://localhost:8761/eureka/
      
      
      
management:
  endpoints:
    web:
      exposure:
        include: info, health


info:
  app:
    name: My Microservice Application
    description: This is a Spring Boot microservice.
    version: 1.0.0

